steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - container_number_recognition_ai  # Replace with your function name
      - --runtime=python312
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=http_request  # Replace with your entry point function
      - --region=us-central1  # Replace with your desired region
      - --max-instances=2
      - --set-secrets=[VISION_ENDPOINT=CNR-VISION_ENDPOINT:latest,VISION_KEY=CNR-CNR-VISION_KEY:latest]

options:
  logging: CLOUD_LOGGING_ONLY